baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '宝烨珠宝'
theme = 'PaperMod'

# 网站参数
[params]
  # 网站描述
  description = "宝烨珠宝 - 专业的珠宝设计与定制服务"
  # 默认主题模式
  defaultTheme = "light"
  # 是否显示目录
  ShowToc = true
  # 是否显示阅读时间
  ShowReadingTime = true
  # 是否显示分享按钮
  ShowShareButtons = true
  # 是否显示文章字数统计
  ShowWordCount = true
  # 是否显示文章更新时间
  ShowLastMod = true

# 导航菜单
[menu]
  [[menu.main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "products"
    name = "产品展示"
    url = "/products/"
    weight = 2
  [[menu.main]]
    identifier = "posts"
    name = "博客"
    url = "/posts/"
    weight = 3
  [[menu.main]]
    identifier = "appointment"
    name = "在线预约"
    url = "/appointment/"
    weight = 4
  [[menu.main]]
    identifier = "contact"
    name = "联系我们"
    url = "/contact/"
    weight = 5

# 社交媒体链接
[params.socialIcons]
  email = "mailto:contact@baoye-jewelry.com"
  phone = "tel:+8612345678900"
  weixin = "weixin"
  weibo = "weibo"

# 忽略警告
ignoreLogs = ['warning-goldmark-raw-html']

# 允许原始 HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 可根据需要添加更多配置
