[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.8"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[plugins]]
  package = "@netlify/plugin-lighthouse" 