backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

locale: 'zh'

collections:
  - name: "posts"
    label: "博客文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "封面图片", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" } 